/*
 * This file is generated by jOOQ.
 */
package notesbackend.jooq.public_;


import notesbackend.jooq.DefaultCatalog;
import notesbackend.jooq.public_.tables.Member;
import notesbackend.jooq.public_.tables.Notes;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.member</code>.
     */
    public final Member MEMBER = Member.MEMBER;

    /**
     * The table <code>public.notes</code>.
     */
    public final Notes NOTES = Notes.NOTES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.USER_ID2_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Member.MEMBER,
            Notes.NOTES
        );
    }
}
