/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.generated.public_;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.user_id2_seq</code>
     */
    public static final Sequence<Integer> USER_ID2_SEQ = Internal.createSequence("user_id2_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
