/*
 * This file is generated by jOOQ.
 */
package notesbackend.jooq.public_;


import notesbackend.jooq.public_.tables.Member;
import notesbackend.jooq.public_.tables.Notes;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.member</code>.
     */
    public static final Member MEMBER = Member.MEMBER;

    /**
     * The table <code>public.notes</code>.
     */
    public static final Notes NOTES = Notes.NOTES;
}
