/*
 * This file is generated by jOOQ.
 */
package notesbackend.jooq.public_.tables.records;


import notesbackend.jooq.public_.tables.Member;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberRecord extends UpdatableRecordImpl<MemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.member.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.member.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.member.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.member.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.member.createdAt</code>.
     */
    public void setCreatedat(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.member.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.member.password</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.member.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberRecord
     */
    public MemberRecord() {
        super(Member.MEMBER);
    }

    /**
     * Create a detached, initialised MemberRecord
     */
    public MemberRecord(Integer id, String name, LocalDateTime createdat, String password) {
        super(Member.MEMBER);

        setId(id);
        setName(name);
        setCreatedat(createdat);
        setPassword(password);
        resetChangedOnNotNull();
    }
}
